#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""fixtures-c4b generator (correction #4B / P0-1.5 + P0-2.6).

Deterministically derives the v2 validator fixture set from ONE hand-authored
positive package:

  wiki/survey/fixtures-c4b/positive_package.json   (committed, hand-authored)
  wiki/survey/fixtures-c4b/N01..N25_*.json         (generated by this script)

Each negative is a NAMED mutation function applied to a deep copy of the
positive — the mutation source code below IS the documentation of what each
negative breaks. Doctoral re-review #4A proved the C4A fixture set covered only
14 failure modes while the prose claimed a full contract; the C4B set adds the
adversarial mutations that review demonstrated (cross-wire, orphan, many-to-one,
empty D2 block, illegal inner enums, seed-threat-tag loss, empty/dangling
DUPLICATE target, malformed disagreements, unbound seed manifest, duplicated
publication_status).

Run from repo root:  python scripts/survey/sf_fixtures_c4b_gen.py
Exit 0 iff all fixtures written; the validator test (sf_record_validator_test.py)
asserts positive==exit 0 and every negative==non-zero subprocess exit.
"""
import copy
import json
import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
FIX = os.path.join(REPO, "wiki", "survey", "fixtures-c4b")
POSITIVE = os.path.join(FIX, "positive_package.json")


def m01_included_missing_rec2_backref(p):
    p["rec0"][0]["extraction"]["rec2_backref"] = None


def m02_excluded_missing_reason_code(p):
    p["rec0"][2]["reason_code"] = None


def m03_claim_backref_to_d1_row(p):
    p["claims"][0]["rec2_backref"] = "REC2-EVOLIB"


def m04_core_row_stuck_at_d1(p):
    p["rec0"][0]["coding_depth"] = "D1"
    p["rec2"][0]["coding_depth"] = "D1"


def m05_duplicate_canonical_id(p):
    p["rec0"][1]["canonical_id"] = p["rec0"][0]["canonical_id"]


def m06_na_as_bare_string(p):
    p["rec2"][1]["matrix"] = "NA: D1 minimal core"


def m07_empty_screener_string(p):
    p["rec0"][0]["screener"] = ""


def m08_decision_enum_drift(p):
    p["rec0"][0]["decision"] = "Included"


def m09_flow_report_hand_tallied_mismatch(p):
    p["flow_report"]["n_included"] = 5


def m10_dangling_rec0_backref(p):
    p["rec2"][1]["rec0_backref"] = "9999.99999"


def m11_missing_study_quality_dim(p):
    del p["rec2"][0]["evidence_axes"]["study_quality"]["data_boundary"]


def m12_threat_without_dual_coding(p):
    del p["rec2"][0]["threat_dual_coding"]


def m13_included_with_reason_code(p):
    p["rec0"][0]["reason_code"] = "NOT_RELEVANT"


def m14_unparseable_source(p):
    p["rec0"][0]["source_hits"][0]["source"] = "google_scholar:manual"


def m15_crosswired_lineage(p):
    a, b = p["rec2"][0], p["rec2"][1]
    a["rec0_backref"], b["rec0_backref"] = b["rec0_backref"], a["rec0_backref"]


def m16_orphan_rec2(p):
    orphan = copy.deepcopy(p["rec2"][1])
    orphan["id"] = "REC2-ORPHAN"
    p["rec2"].append(orphan)


def m17_many_to_one_lineage(p):
    p["rec0"][1]["extraction"]["rec2_backref"] = "REC2-AMC"


def m18_empty_d2_block(p):
    p["rec2"][0]["matrix"] = {}


def m19_illegal_inner_enum(p):
    p["rec2"][0]["matrix"]["parameter_update"] = "NOT_AN_ENUM_VALUE"
    p["rec2"][0]["tf_audit"]["base_model_updated"] = ""
    p["rec2"][0]["source_axes"]["activation_attribution"] = "magic"


def m20_seed_threat_tag_deleted(p):
    p["rec2"][0]["initial_tag"] = []
    del p["rec2"][0]["threat_dual_coding"]


def m21_empty_duplicate_target(p):
    p["rec0"][3]["reason_code"] = "DUPLICATE_OF:"


def m22_dangling_duplicate_target(p):
    p["rec0"][3]["reason_code"] = "DUPLICATE_OF:1234.56789"


def m23_bad_disagreements_type(p):
    p["rec2"][0]["threat_dual_coding"]["disagreements"] = "two"


def m24_seed_manifest_unbound(p):
    del p["seed_manifest"]


def m25_toplevel_publication_status(p):
    p["rec2"][0]["publication_status"] = "preprint"


MUTATIONS = [
    m01_included_missing_rec2_backref, m02_excluded_missing_reason_code,
    m03_claim_backref_to_d1_row, m04_core_row_stuck_at_d1,
    m05_duplicate_canonical_id, m06_na_as_bare_string,
    m07_empty_screener_string, m08_decision_enum_drift,
    m09_flow_report_hand_tallied_mismatch, m10_dangling_rec0_backref,
    m11_missing_study_quality_dim, m12_threat_without_dual_coding,
    m13_included_with_reason_code, m14_unparseable_source,
    m15_crosswired_lineage, m16_orphan_rec2, m17_many_to_one_lineage,
    m18_empty_d2_block, m19_illegal_inner_enum, m20_seed_threat_tag_deleted,
    m21_empty_duplicate_target, m22_dangling_duplicate_target,
    m23_bad_disagreements_type, m24_seed_manifest_unbound,
    m25_toplevel_publication_status,
]


def main():
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")
    with open(POSITIVE, encoding="utf-8") as f:
        positive = json.load(f)
    written = []
    for i, fn in enumerate(MUTATIONS, 1):
        pkg = copy.deepcopy(positive)
        fn(pkg)
        name = f"N{i:02d}_{fn.__name__[4:]}.json"
        path = os.path.join(FIX, name)
        with open(path, "w", encoding="utf-8", newline="\n") as f:
            json.dump(pkg, f, ensure_ascii=False, indent=1, sort_keys=True)
            f.write("\n")
        written.append(name)
    print(f"wrote {len(written)} negatives from positive_package.json -> fixtures-c4b/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
