# -*- coding: utf-8 -*-
import re, json, os

OUTDIR = "/mnt/d/chao_workspace/exploring-l4-intelligence/papers/agent-level-tfrl"
os.makedirs(OUTDIR, exist_ok=True)

# (key, Title, URL) — key is a stable, collision-free, human-meaningful BibTeX key.
ENTRIES = [
# 1. Training-free RL theory, inference-time tilting & output-level convergence
("korbak2022kl","RL with KL penalties is better viewed as Bayesian inference","https://arxiv.org/abs/2205.11275"),
("beirami2024bon","Theoretical guarantees on the best-of-n alignment policy","https://arxiv.org/abs/2401.01879"),
("gui2024bonbon","BoNBoN Alignment for LLMs and the Sweetness of Best-of-n Sampling","https://arxiv.org/abs/2406.00832"),
("yang2024asymptotics","Asymptotics of Language Model Alignment","https://arxiv.org/abs/2404.01730"),
("verdun2025softbon","Soft Best-of-n Sampling for Model Alignment","https://arxiv.org/abs/2505.03156"),
("aminian2025smoothing","Best-of-N through the Smoothing Lens: KL Divergence and Regret Analysis","https://arxiv.org/abs/2507.05913"),
("ichihara2025mbr","Theoretical Guarantees for Minimum Bayes Risk Decoding","https://arxiv.org/abs/2502.12685"),
("mbrasr2025","Re-evaluating Minimum Bayes Risk Decoding for Automatic Speech Recognition","https://arxiv.org/abs/2510.19471"),
("jinnai2024mbrbon","Regularized Best-of-N Sampling with Minimum Bayes Risk Objective for LM Alignment","https://arxiv.org/abs/2404.01054"),
("mudgal2024controlled","Controlled Decoding from Language Models","https://arxiv.org/abs/2310.17022"),
("wang2023selfconsistency","Self-Consistency Improves Chain of Thought Reasoning in Language Models","https://arxiv.org/abs/2203.11171"),
("zuo2025ttrl","TTRL: Test-Time Reinforcement Learning","https://arxiv.org/abs/2504.16084"),
("li2025tpo","Test-Time Preference Optimization: On-the-Fly Alignment via Iterative Textual Feedback","https://arxiv.org/abs/2501.12895"),
("jitrl2026","Just-In-Time Reinforcement Learning: Continual Learning in LLM Agents Without Gradient Updates (ICML 2026 Spotlight)","https://arxiv.org/abs/2601.18510"),
("khalaf2025hedgetune","Inference-Time Reward Hacking in Large Language Models (HedgeTune, Best-of-Poisson)","https://arxiv.org/abs/2506.19248"),
("gao2023overopt","Scaling Laws for Reward Model Overoptimization","https://arxiv.org/abs/2210.10760"),
("geuter2025gsi","Guided Speculative Inference for Efficient Test-Time Alignment of LLMs","https://arxiv.org/abs/2506.04118"),
("carbon2025","CarBoN: Calibrated Best-of-N Sampling Improves Test-time Reasoning","https://arxiv.org/abs/2510.15674"),
("certifiedsc2025","Certified Self-Consistency: Statistical Guarantees and Test-Time Training for Reliable Reasoning","https://arxiv.org/abs/2510.17472"),
("cges2025","CGES: Confidence-Guided Early Stopping for Efficient Sampling","https://arxiv.org/abs/2511.02603"),
("reasc2026","Reliability-Aware Adaptive Self-Consistency (ReASC)","https://arxiv.org/abs/2601.02970"),
("snell2024ttscompute","Scaling LLM Test-Time Compute Optimally can be More Effective than Scaling Model Parameters","https://arxiv.org/abs/2408.03314"),
("t3rl2026","Tool Verification for Test-Time Reinforcement Learning (T3RL)","https://arxiv.org/abs/2603.02203"),
("zhao2024twistedsmc","Probabilistic Inference in Language Models via Twisted Sequential Monte Carlo","https://arxiv.org/abs/2404.17546"),
("singhal2025fksteering","A General Framework for Inference-time Scaling and Steering of Diffusion Models (FK steering)","https://arxiv.org/abs/2501.06848"),
("pgdlm2025","Inference-Time Scaling of Diffusion Language Models with Particle Gibbs Sampling","https://arxiv.org/abs/2507.08390"),
("ahmadian2024rloo","Back to Basics: Revisiting REINFORCE Style Optimization (RLOO)","https://arxiv.org/abs/2402.14740"),
("greensmith2004variance","Variance Reduction Techniques for Gradient Estimates in Reinforcement Learning","https://www.jmlr.org/papers/volume5/greensmith04a/greensmith04a.pdf"),
("kocsis2006uct","Bandit Based Monte-Carlo Planning (UCT)","https://link.springer.com/chapter/10.1007/11871842_29"),
("yang2023tap","Generative Speech Recognition Error Correction with LLMs and Task-Activating Prompting","https://arxiv.org/abs/2309.15649"),
("ma2023asrgec","Can Generative Large Language Models perform ASR error correction?","https://arxiv.org/abs/2307.04172"),
("asrgec2024","ASR Error Correction using Large Language Models","https://arxiv.org/abs/2409.09554"),
# 2. RLVR boundary, reward hacking, verifiable rewards
("rlvrincentive2025","RLVR Implicitly Incentivizes Correct Reasoning in Base LLMs","https://arxiv.org/abs/2506.14245"),
("newskills2026","New Skills or Sharper Primitives? A Probabilistic Perspective on the Emergence of Reasoning in RLVR","https://arxiv.org/abs/2602.08281"),
("rlvrdebate2025","The Debate on RLVR Reasoning Capability Boundary: Shrinkage, Expansion, or Both?","https://arxiv.org/abs/2510.04028"),
("spuriousrewards2025","Spurious Rewards: Rethinking Training Signals in RLVR","https://arxiv.org/abs/2506.10947"),
("skalse2022rewardhacking","Defining and Characterizing Reward Hacking","https://arxiv.org/abs/2209.13085"),
("tulu3","Tulu 3: Pushing Frontiers in Open Language Model Post-Training","https://arxiv.org/abs/2411.15124"),
# 3. ICL / few-shot in audio LLMs & text-ICL
("min2022rethinking","Rethinking the Role of Demonstrations: What Makes In-Context Learning Work?","https://arxiv.org/abs/2202.12837"),
("yoo2022groundtruth","Ground-Truth Labels Matter: A Deeper Look into Input-Label Demonstrations","https://arxiv.org/abs/2205.12685"),
("wei2023larger","Larger language models do in-context learning differently","https://arxiv.org/abs/2303.03846"),
("alice2026","ALICE: A Multifaceted Evaluation Framework of Large Audio-Language Models In-Context Learning Ability","https://arxiv.org/abs/2603.20433"),
("hsu2023iclspeech","Exploring In-Context Learning of Textless Speech Language Model for Speech Classification Tasks","https://arxiv.org/abs/2310.12477"),
("fsagrpo2026","FSA-GRPO: Teaching Auditory LLMs to Use Few-shot Demonstrations","https://arxiv.org/abs/2606.02615"),
("mimoaudio2025","MiMo-Audio: Audio Language Models are Few-Shot Learners","https://arxiv.org/abs/2512.23808"),
("uniaudio15","UniAudio 1.5: LLM-driven Audio Codec is a Few-shot Audio Task Learner","https://arxiv.org/abs/2406.10056"),
("pouw2026iclspeech","In-Context Learning in Speech Language Models: Acoustic Features, Linguistic Structure, and Induction Heads","https://arxiv.org/abs/2604.06356"),
("todd2024functionvectors","Function Vectors in Large Language Models","https://arxiv.org/abs/2310.15213"),
("taskvectors2025","Task Vectors in In-Context Learning: Emergence, Formation, and Benefits","https://arxiv.org/abs/2501.09240"),
("sericl2025","Few-shot Personalization via In-Context Learning for Speech Emotion Recognition based on Speech-LM","https://arxiv.org/abs/2509.08344"),
("bgeenicl2024","Making Text Embedders Few-Shot Learners (bge-en-icl)","https://arxiv.org/abs/2409.15700"),
("su2023instructor","One Embedder, Any Task: Instruction-Finetuned Text Embeddings (INSTRUCTOR)","https://arxiv.org/abs/2212.09741"),
("inbedder2024","Answer is All You Need: Instruction-following Text Embedding via Answering the Question (InBedder)","https://arxiv.org/abs/2402.09642"),
# 4. Capability map / model classes / embedding geometry / probing
("qwen25omni","Qwen2.5-Omni Technical Report","https://arxiv.org/abs/2503.20215"),
("qwen3omni","Qwen3-Omni Technical Report","https://arxiv.org/abs/2509.17765"),
("qwen2audio","Qwen2-Audio Technical Report","https://arxiv.org/abs/2407.10759"),
("qwenaudio","Qwen-Audio: Advancing Universal Audio Understanding","https://arxiv.org/abs/2311.07919"),
("salmonn2023","SALMONN: Towards Generic Hearing Abilities for Large Language Models","https://arxiv.org/abs/2310.13289"),
("omniembed2025","Omni-Embed-Nemotron: A Unified Multimodal Retrieval Model for Text, Image, Audio, and Video","https://arxiv.org/abs/2510.03458"),
("omniembedaudio2026","Omni-Embed-Audio: Leveraging Multimodal LLMs for Robust Audio-Text Retrieval","https://arxiv.org/abs/2604.18360"),
("whisper2022","Robust Speech Recognition via Large-Scale Weak Supervision (Whisper)","https://arxiv.org/abs/2212.04356"),
("seamlessm4t","SeamlessM4T: Massively Multilingual and Multimodal Machine Translation","https://arxiv.org/abs/2308.11596"),
("seamless2023","Seamless: Multilingual Expressive and Streaming Speech Translation","https://arxiv.org/abs/2312.05187"),
("clap2022","CLAP: Learning Audio Concepts From Natural Language Supervision","https://arxiv.org/abs/2206.04769"),
("nvembed2024","NV-Embed: Improved Techniques for Training LLMs as Generalist Embedding Models","https://arxiv.org/abs/2405.17428"),
("mmteb2025","MMTEB: Massive Multilingual Text Embedding Benchmark","https://arxiv.org/abs/2502.13595"),
("instructir2024","INSTRUCTIR: A Benchmark for Instruction Following of Information Retrieval Models","https://arxiv.org/abs/2402.14334"),
("diffvsar2025","Diffusion vs. Autoregressive Language Models: A Text Embedding Perspective","https://arxiv.org/abs/2505.15045"),
("simcse2021","SimCSE: Simple Contrastive Learning of Sentence Embeddings","https://arxiv.org/abs/2104.08821"),
("wang2020alignuniform","Understanding Contrastive Representation Learning through Alignment and Uniformity on the Hypersphere","https://arxiv.org/abs/2005.10242"),
("xiao2020whatnot","What Should Not Be Contrastive in Contrastive Learning","https://arxiv.org/abs/2008.05659"),
("leace2023","LEACE: Perfect linear concept erasure in closed form","https://arxiv.org/abs/2306.03819"),
("superb2021","SUPERB: Speech processing Universal PERformance Benchmark","https://arxiv.org/abs/2105.01051"),
("dynsuperb2023","Dynamic-SUPERB: A Dynamic, Collaborative, Comprehensive Instruction-Tuning Benchmark for Speech","https://arxiv.org/abs/2309.09510"),
("dynsuperb2","Dynamic-SUPERB Phase-2","https://arxiv.org/abs/2411.05361"),
("slurp2020","SLURP: A Spoken Language Understanding Resource Package","https://aclanthology.org/2020.emnlp-main.588/"),
("airbench2024","AIR-Bench: Benchmarking Large Audio-Language Models via Generative Comprehension","https://arxiv.org/abs/2402.07729"),
("mmau2024","MMAU: A Massive Multi-Task Audio Understanding and Reasoning Benchmark","https://arxiv.org/abs/2410.19168"),
("frozenllmparaling2024","Frozen Large Language Models Can Perceive Paralinguistic Aspects of Speech","https://arxiv.org/abs/2410.01162"),
("paralingreason2025","Benchmarking Contextual and Paralinguistic Reasoning in Speech-LLMs","https://arxiv.org/abs/2509.16589"),
("emotionneurons2026","Discovering and Causally Validating Emotion-Sensitive Neurons in Large Audio-Language Models","https://arxiv.org/abs/2601.03115"),
("voxparadox2026","Do Audio LLMs Listen or Read? Analyzing and Mitigating Paralinguistic Failures with VoxParadox","https://arxiv.org/abs/2605.27772"),
("listenortranscribe2025","Do Audio LLMs Really LISTEN, or Just Transcribe? Measuring Lexical vs. Acoustic Emotion Cues Reliance","https://arxiv.org/abs/2510.10444"),
("spkverifllm2026","Speaker Verification with Speech-Aware LLMs: Evaluation and Augmentation","https://arxiv.org/abs/2603.10827"),
("emosllm2025","EmoSLLM: Parameter-Efficient Adaptation of LLMs for Speech Emotion Recognition","https://arxiv.org/abs/2508.14130"),
("paralingrl2026","Aligning Paralinguistic Understanding and Generation in Speech LLMs via Multi-Task RL","https://arxiv.org/abs/2603.15981"),
("attnstatspool2018","Attentive Statistics Pooling for Deep Speaker Embedding","https://arxiv.org/abs/1803.10963"),
("ecapatdnn2020","ECAPA-TDNN: Emphasized Channel Attention, Propagation and Aggregation in TDNN","https://arxiv.org/abs/2005.07143"),
("pasad2021layerwise","Layer-wise Analysis of a Self-supervised Speech Representation Model","https://arxiv.org/abs/2107.04734"),
("comparativelayerwise2022","Comparative layer-wise analysis of self-supervised speech models","https://arxiv.org/abs/2211.03929"),
("sslwords2024","What Do Self-Supervised Speech Models Know About Words?","https://doi.org/10.1162/tacl_a_00656"),
("crossmodellayerwise2024","What do self-supervised speech and speaker models learn? Cross-model layer-wise analysis","https://arxiv.org/abs/2401.17632"),
("spkattrprobing2025","A Large-Scale Probing Analysis of Speaker-Specific Attributes in SSL Speech Representations","https://arxiv.org/abs/2501.05310"),
("crossmodalencode2024","How do Multimodal Foundation Models Encode Text and Speech?","https://arxiv.org/abs/2411.17666"),
# 5. Verifiable rewards, eval, leakage, reproducibility
("roelofs2019overfitting","A Meta-Analysis of Overfitting in Machine Learning","https://papers.nips.cc/paper/9117-a-meta-analysis-of-overfitting-in-machine-learning"),
("contaminationsurvey2024","Benchmark Data Contamination of Large Language Models: A Survey","https://arxiv.org/abs/2406.04244"),
("bisani2004bootstrap","Bootstrap estimates for confidence intervals in ASR performance evaluation","https://ieeexplore.ieee.org/document/1326009"),
("positionbias2024","Judging the Judges: A Systematic Study of Position Bias in LLM-as-a-Judge","https://arxiv.org/abs/2406.07791"),
("selfpreference2024","Self-Preference Bias in LLM-as-a-Judge","https://arxiv.org/abs/2410.21819"),
("pineau2020reproducibility","Improving Reproducibility in Machine Learning Research","https://arxiv.org/abs/2003.12206"),
("dodge2019showyourwork","Show Your Work: Improved Reporting of Experimental Results","https://arxiv.org/abs/1909.03004"),
("taskcontamination2024","Task Contamination: Language Models May Not Be Few-Shot Anymore","https://ojs.aaai.org/index.php/AAAI/article/view/29808"),
("dror2018hitchhiker","The Hitchhiker's Guide to Testing Statistical Significance in NLP","https://aclanthology.org/P18-1128/"),
("dwork2015reusable","The reusable holdout: Preserving validity in adaptive data analysis","https://doi.org/10.1126/science.aaa9375"),
("tinybenchmarks2024","tinyBenchmarks: evaluating LLMs with fewer examples","https://arxiv.org/abs/2402.14992"),
("perez2021truefewshot","True Few-Shot Learning with Language Models","https://arxiv.org/abs/2105.11447"),
("gorman2019splits","We Need to Talk about Standard Splits","https://aclanthology.org/P19-1267/"),
("card2020power","With Little Power Comes Great Responsibility","https://arxiv.org/abs/2010.06595"),
("henderson2018drlmatters","Deep Reinforcement Learning that Matters","https://arxiv.org/abs/1709.06560"),
# 6. Agent memory
("rag2020","Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks","https://arxiv.org/abs/2005.11401"),
("genagents2023","Generative Agents: Interactive Simulacra of Human Behavior","https://arxiv.org/abs/2304.03442"),
("memgpt2023","MemGPT: Towards LLMs as Operating Systems","https://arxiv.org/abs/2310.08560"),
("memsurvey2026","Memory for Autonomous LLM Agents: Mechanisms, Evaluation, and Emerging Frontiers","https://arxiv.org/abs/2603.07670"),
("memorybank2023","MemoryBank: Enhancing Large Language Models with Long-Term Memory","https://arxiv.org/abs/2305.10250"),
("amem2025","A-MEM: Agentic Memory for LLM Agents","https://arxiv.org/abs/2502.12110"),
("arigraph2024","AriGraph: Learning Knowledge Graph World Models with Episodic Memory for LLM Agents","https://arxiv.org/abs/2407.04363"),
("hipporag2024","HippoRAG: Neurobiologically Inspired Long-Term Memory for LLMs","https://arxiv.org/abs/2405.14831"),
("hipporag2_2025","From RAG to Memory: Non-Parametric Continual Learning for LLMs (HippoRAG 2)","https://arxiv.org/abs/2502.14802"),
("zep2025","Zep: A Temporal Knowledge Graph Architecture for Agent Memory","https://arxiv.org/abs/2501.13956"),
("mem0_2025","Mem0: Building Production-Ready AI Agents with Scalable Long-Term Memory","https://arxiv.org/abs/2504.19413"),
("memoryos2025","Memory OS of AI Agent (MemoryOS)","https://arxiv.org/abs/2506.06326"),
("colbert2020","ColBERT: Efficient and Effective Passage Search via Contextualized Late Interaction over BERT","https://arxiv.org/abs/2004.12832"),
("memoryr1_2025","Memory-R1: Enhancing LLM Agents to Manage and Utilize Memories via Reinforcement Learning","https://arxiv.org/abs/2508.19828"),
("agentpoison2024","AgentPoison: Red-teaming LLM Agents via Poisoning Memory or Knowledge Bases","https://arxiv.org/abs/2407.12784"),
("memorygraft2025","MemoryGraft: Persistent Compromise of LLM Agents via Poisoned Experience Retrieval","https://arxiv.org/abs/2512.16962"),
("mempoison2026","Memory Poisoning Attack and Defense on Memory-Based LLM Agents","https://arxiv.org/abs/2601.05504"),
("anatomymem2026","Anatomy of Agentic Memory: Taxonomy and Empirical Analysis of Evaluation and System Limitations","https://arxiv.org/abs/2602.19320"),
("wavrag2025","WavRAG: Audio-Integrated Retrieval Augmented Generation for Spoken Dialogue Models","https://arxiv.org/abs/2502.14727"),
("speechrag2024","Speech Retrieval-Augmented Generation without Automatic Speech Recognition (SpeechRAG)","https://arxiv.org/abs/2412.16500"),
("seal2025","SEAL: Speech Embedding Alignment Learning for Speech LLM with RAG","https://arxiv.org/abs/2502.02603"),
("voxrag2025","VoxRAG: A Step Toward Transcription-Free RAG Systems in Spoken Question Answering","https://arxiv.org/abs/2505.17326"),
("moshirag2026","MoshiRAG: Asynchronous Knowledge Retrieval for Full-Duplex Speech Language Models","https://arxiv.org/abs/2604.12928"),
("amber2026","A-MBER: Affective Memory Benchmark for Emotion Recognition","https://arxiv.org/abs/2604.07017"),
("memgallery2026","Mem-Gallery: Benchmarking Multimodal Long-Term Conversational Memory for MLLM Agents","https://arxiv.org/abs/2601.03515"),
("omnisimplemem2026","Omni-SimpleMem: Autoresearch-Guided Discovery of Lifelong Multimodal Agent Memory","https://arxiv.org/abs/2604.01007"),
("longmemeval2024","LongMemEval: Benchmarking Chat Assistants on Long-Term Interactive Memory","https://arxiv.org/abs/2410.10813"),
("locomo2024","Evaluating Very Long-Term Conversational Memory of LLM Agents (LoCoMo)","https://arxiv.org/abs/2402.17753"),
("mempal2025","Mem-PAL: Towards Memory-based Personalized Dialogue Assistants for Long-term User-Agent Interaction","https://arxiv.org/abs/2511.13410"),
("vehiclemembench2026","VehicleMemBench: Executable Benchmark for Multi-User Long-Term Memory in In-Vehicle Agents","https://arxiv.org/abs/2603.23840"),
("xvector2021","X-Vectors with Multi-Scale Aggregation for Speaker Diarization","https://arxiv.org/abs/2105.07367"),
("personalvad2019","Personal VAD: Speaker-Conditioned Voice Activity Detection","https://arxiv.org/abs/1908.04284"),
("memsurvey2_2024","From Human Memory to AI Memory: A Survey on Memory Mechanisms in the Era of LLMs","https://arxiv.org/abs/2504.15965"),
# 7. Agent skills
("skillsbench2026","SkillsBench: Benchmarking How Well Agent Skills Work Across Diverse Tasks","https://arxiv.org/abs/2602.12670"),
("sokskills2026","SoK: Agentic Skills - Beyond Tool Use in LLM Agents","https://arxiv.org/abs/2602.20867"),
("coevoskills2026","CoEvoSkills: Self-Evolving Agent Skills via Co-Evolutionary Verification","https://arxiv.org/abs/2604.01687"),
("skillrouter2026","SkillRouter: Retrieve-and-Rerank Skill Selection for LLM Agents at Scale","https://arxiv.org/abs/2603.22455"),
("voyager2023","Voyager: An Open-Ended Embodied Agent with Large Language Models","https://arxiv.org/abs/2305.16291"),
("creator2023","CREATOR: Tool Creation for Disentangling Abstract and Concrete Reasoning of LLMs","https://arxiv.org/abs/2305.14318"),
("craft2023","CRAFT: Customizing LLMs by Creating and Retrieving from Specialized Toolsets","https://arxiv.org/abs/2309.17428"),
("aflow2024","AFlow: Automating Agentic Workflow Generation","https://arxiv.org/abs/2410.10762"),
("agentsquare2024","AgentSquare: Automatic LLM Agent Search in Modular Design Space","https://arxiv.org/abs/2410.06153"),
("gepa2025","GEPA: Reflective Prompt Evolution Can Outperform Reinforcement Learning","https://arxiv.org/abs/2507.19457"),
("awm2024","Agent Workflow Memory","https://arxiv.org/abs/2409.07429"),
("polyskill2025","PolySkill: Learning Generalizable Skills Through Polymorphic Abstraction For Continual Learning","https://arxiv.org/abs/2510.15863"),
("skillgraph2026","SkillGraph: Skill-Augmented RL for Agents via Evolving Skill Graphs","https://arxiv.org/abs/2605.12039"),
(" gerrarewords2025".strip(),"LLM-based Generative Error Correction for Rare Words with Synthetic Data and Phonetic Context","https://arxiv.org/abs/2505.17410"),
("denoisingger2025","Denoising GER: A Noise-Robust Generative Error Correction with LLM for Speech Recognition","https://arxiv.org/abs/2509.04392"),
("aura2025","AURA: Agent for Understanding, Reasoning, and Automated Tool Use in Voice-Driven Tasks","https://arxiv.org/abs/2506.23049"),
("paras2s2025","ParaS2S: Benchmarking and Aligning Spoken Language Models for Paralinguistic-aware S2S Interaction","https://arxiv.org/abs/2511.08723"),
("gsrm2026","GSRM: Generative Speech Reward Model for Speech RLHF","https://arxiv.org/abs/2602.13891"),
("skillret2026","SkillRet: A Large-Scale Benchmark for Skill Retrieval in LLM Agents","https://arxiv.org/abs/2605.05726"),
("skillfoundry2026","SKILLFOUNDRY: Building Self-Evolving Agent Skill Libraries from Heterogeneous Scientific Resources","https://arxiv.org/abs/2604.03964"),
("textgrad2024","TextGrad: Automatic Differentiation via Text","https://arxiv.org/abs/2406.07496"),
("trace2024","Trace is the Next AutoDiff (OptoPrime)","https://arxiv.org/abs/2406.16218"),
("dspy2023","DSPy: Compiling Declarative Language Model Calls into Self-Improving Pipelines","https://arxiv.org/abs/2310.03714"),
("adas2024","Automated Design of Agentic Systems (ADAS)","https://arxiv.org/abs/2408.08435"),
("expel2023","ExpeL: LLM Agents Are Experiential Learners","https://arxiv.org/abs/2308.10144"),
("selfevolvesurvey2025","A Survey of Self-Evolving Agents: What, When, How, and Where to Evolve","https://arxiv.org/abs/2507.21046"),
("museautoskill2026","MUSE-Autoskill: Self-Evolving Agents via Skill Creation, Memory, Management, and Evaluation","https://arxiv.org/abs/2605.27366"),
("memskill2026","MemSkill: Learning and Evolving Memory Skills for Self-Evolving Agents","https://arxiv.org/abs/2602.02474"),
("memoria2025","Memoria: A Scalable Agentic Memory Framework for Personalized Conversational AI","https://arxiv.org/abs/2512.12686"),
("jarvis2025","Jarvis: Towards Personalized AI Assistant via Personal KV-Cache Retrieval","https://arxiv.org/abs/2510.22765"),
# 8. Agent-level convergence, stability, credit assignment
("reflexion2023","Reflexion: Language Agents with Verbal Reinforcement Learning","https://arxiv.org/abs/2303.11366"),
("lats2023","Language Agent Tree Search Unifies Reasoning, Acting, and Planning in Language Models (LATS)","https://arxiv.org/abs/2310.04406"),
("ace2025","Agentic Context Engineering: Evolving Contexts for Self-Improving Language Models (ACE)","https://arxiv.org/abs/2510.04618"),
("agentq2024","Agent Q: Advanced Reasoning and Learning for Autonomous AI Agents","https://arxiv.org/abs/2408.07199"),
("memento2025","Memento: Fine-tuning LLM Agents without Fine-tuning LLMs","https://arxiv.org/abs/2508.16153"),
("expfollowing2025","How Memory Management Impacts LLM Agents: Empirical Study of Experience-Following Behavior","https://arxiv.org/abs/2505.16067"),
("ssgm2026","Governing Evolving Memory in LLM Agents: Risks, Mechanisms, and the SSGM Framework","https://arxiv.org/abs/2603.11768"),
("remembering2026","Remembering More, Risking More: Longitudinal Safety Risks in Memory-Equipped LLM Agents","https://arxiv.org/abs/2605.17830"),
("oprl2025","Online Process Reward Learning for Agentic Reinforcement Learning (OPRL/iStar)","https://arxiv.org/abs/2509.19199"),
("agentprm2025","AgentPRM: Process Reward Models for LLM Agents via Step-Wise Promise and Progress","https://arxiv.org/abs/2511.08325"),
("cer2025","Contextual Experience Replay for Self-Improvement of Language Agents (CER)","https://arxiv.org/abs/2506.06698"),
# 9. Speech agents & benchmarks
("urobench2025","URO-Bench: Towards Comprehensive Evaluation for End-to-End Spoken Dialogue Models","https://arxiv.org/abs/2502.17810"),
("voicebench2024","VoiceBench: Benchmarking LLM-Based Voice Assistants","https://arxiv.org/abs/2410.17196"),
("voiceassistanteval2025","VoiceAssistant-Eval: Benchmarking AI Assistants across Listening, Speaking, and Viewing","https://arxiv.org/abs/2509.22651"),
("vocalbench2025","VocalBench: Benchmarking the Vocal Conversational Abilities for Speech Interaction Models","https://arxiv.org/abs/2505.15727"),
("taubench2024","tau-bench: A Benchmark for Tool-Agent-User Interaction in Real-World Domains","https://arxiv.org/abs/2406.12045"),
("fullduplexbench2025","Full-Duplex-Bench: Evaluate Full-Duplex Spoken Dialogue Models on Turn-taking Capabilities","https://arxiv.org/abs/2503.04721"),
("fullduplexbenchv3_2026","Full-Duplex-Bench-v3: Benchmarking Tool Use for Full-Duplex Voice Agents Under Real-World Disfluency","https://arxiv.org/abs/2604.04847"),
("audiomc2025","Audio MultiChallenge: A Multi-Turn Evaluation of Spoken Dialogue Systems (AudioMC)","https://arxiv.org/abs/2512.14865"),
("multibench2025","MULTI-Bench: A Multi-Turn Interactive Benchmark for Emotional Intelligence of Spoken Dialogue Models","https://arxiv.org/abs/2511.00850"),
("evabench2026","EVA-Bench: A New End-to-end Framework for Evaluating Voice Agents","https://arxiv.org/abs/2605.13841"),
("cortis2026","CORTIS: Text-Only Adaptation of Spoken Language Models for Task-Oriented Voice Agents","https://arxiv.org/abs/2606.21453"),
("soulxduplug2026","SoulX-Duplug: Plug-and-Play Streaming State Prediction Module for Realtime Full-Duplex Speech","https://arxiv.org/abs/2603.14877"),
("exprspeechretrieval2025","Expressive Speech Retrieval using Natural Language Descriptions of Speaking Style","https://arxiv.org/abs/2508.11187"),
("verifiagent2025","VerifiAgent: a Unified Verification Agent in Language Model Reasoning","https://arxiv.org/abs/2504.00406"),
("tauvoice2026","tau-Voice: Voice Tool-Use Benchmark","https://arxiv.org/abs/2603.13686"),
# 10. Selected code repos / model weights
("jitrlcode","JitRL official code","https://github.com/liushiliushi/JitRL"),
("hedgetunecode","HedgeTune (official code)","https://github.com/hskhalaf/hedging"),
("gsicode","Guided Speculative Inference (GSI) code","https://github.com/j-geuter/GSI"),
("acecode","ACE official code","https://github.com/ace-agent/ace"),
("awmcode","Agent Workflow Memory code","https://github.com/zorazrw/agent-workflow-memory"),
("mem0code","Mem0 code","https://github.com/mem0ai/mem0"),
("graphiticode","Graphiti temporal KG engine","https://github.com/getzep/graphiti"),
("hipporagcode","HippoRAG code","https://github.com/OSU-NLP-Group/HippoRAG"),
("pyannotecode","pyannote-audio (diarization)","https://github.com/pyannote/pyannote-audio"),
("coevoskillscode","CoEvoSkills code","https://github.com/Zhang-Henry/CoEvoSkills"),
("skillroutercode","SkillRouter code","https://github.com/zhengyanzhao1997/SkillRouter"),
("gepacode","GEPA code","https://github.com/gepa-ai/gepa"),
("anthropicskills","anthropics/skills (Agent Skills repo)","https://github.com/anthropics/skills"),
("anthropicskillsblog","Equipping agents for the real world with Agent Skills","https://www.anthropic.com/engineering/equipping-agents-for-the-real-world-with-agent-skills"),
("omniembedweights","nvidia/omni-embed-nemotron-3b model weights","https://huggingface.co/nvidia/omni-embed-nemotron-3b"),
("lettasleeptime","Sleep-time Compute (Letta)","https://www.letta.com/blog/sleep-time-compute/"),
# 11. Probing/IB classics from the W4 feasibility doc
("rlace2022","Linear Adversarial Concept Erasure (RLACE)","https://proceedings.mlr.press/v162/ravfogel22a.html"),
("alain2016probes","Understanding intermediate layers using linear classifier probes","https://arxiv.org/abs/1610.01644"),
("tishby2015ib","Deep Learning and the Information Bottleneck Principle","https://arxiv.org/abs/1503.02406"),
]

def detect_type(url):
    return "arxiv" if "arxiv.org/abs/" in url else "other"

def arxiv_id(url):
    m = re.search(r'arxiv\.org/abs/(\d{4}\.\d{4,5})', url)
    return m.group(1) if m else None

# sanity: unique keys
keys = [e[0] for e in ENTRIES]
assert len(keys) == len(set(keys)), "DUP KEYS: " + str([k for k in keys if keys.count(k)>1])

lines = ["% Auto-generated bibliography for the W5 agent-level TFRL proposal.",
         "% " + str(len(ENTRIES)) + " adversarially-verified sources. Do not hand-edit keys.", ""]
keymap = {}
for key, title, url in ENTRIES:
    keymap[title] = key
    aid = arxiv_id(url)
    safe_title = title.replace("{","").replace("}","")
    if aid:
        lines.append("@article{%s,\n  title={{%s}},\n  journal={arXiv preprint arXiv:%s},\n  eprint={%s},\n  archivePrefix={arXiv},\n  url={%s},\n  year={20%s}\n}" % (
            key, safe_title, aid, aid, url, aid[:2]))
    else:
        lines.append("@misc{%s,\n  title={{%s}},\n  howpublished={\\url{%s}}\n}" % (
            key, safe_title, url))
    lines.append("")

open(OUTDIR + "/references.bib","w",encoding="utf-8").write("\n".join(lines))
json.dump(keymap, open("/mnt/c/Users/35686/AppData/Local/Temp/claude/D--chao-workspace-exploring-l4-intelligence-projects-speech-mllm-training-free-rl/cbe193a3-c6e4-4827-9482-f4379759edd9/scratchpad/keymap.json","w",encoding="utf-8"), ensure_ascii=False, indent=0)
print("wrote references.bib with %d entries" % len(ENTRIES))
print("unique keys:", len(set(keys)))
